-- JOINS
CREATE TABLE EMPLOYEE(E_ID INT, E_NAME VARCHAR(10), SALARY INT, D_ID VARCHAR(5));
INSERT INTO EMPLOYEE VALUES(11,"JOHN",25000,"D1"),
						   (12,"ASHI",34000,"D2"),
                           (13,"KRISH",20000,"D3"),
                           (14,"VIDHI",45000,"D4"),
                           (15,"JOE",50000,"D7");
                           
CREATE TABLE DEPARTMENT(D_ID VARCHAR (5), D_NAME VARCHAR (15));
INSERT INTO DEPARTMENT VALUES("D1","HR"),
                             ("D2","SALES"),
                             ("D3","MANAGER"),
                             ("D4", "IT"),
                             ("D5","FINANCE");

-- INNER JOIN
SELECT EMPLOYEE.E_ID, EMPLOYEE.SALARY, DEPARTMENT.D_ID, DEPARTMENT.D_NAME
FROM EMPLOYEE INNER JOIN DEPARTMENT
ON EMPLOYEE.D_ID = DEPARTMENT.D_ID;


-- USING ALIASES
SELECT E.E_ID, E.SALARY, D.D_ID, D.D_NAME
FROM EMPLOYEE AS E INNER JOIN DEPARTMENT AS D
ON E.D_ID = D.D_ID;

SELECT * FROM EMPLOYEE INNER JOIN DEPARTMENT
ON EMPLOYEE.D_ID = DEPARTMENT.D_ID;

-- LEFT JOIN
SELECT E.E_ID, E.SALARY,E.D_ID, D.D_ID, D.D_NAME
FROM EMPLOYEE AS E LEFT JOIN DEPARTMENT AS D
ON E.D_ID = D.D_ID;

-- RIGHT JOIN
SELECT E.E_ID, E.SALARY,E.D_ID, D.D_ID, D.D_NAME
FROM EMPLOYEE AS E RIGHT JOIN DEPARTMENT AS D
ON E.D_ID = D.D_ID;

-- FULL OUTER JOIN
SELECT E.E_ID, E.SALARY,E.D_ID, D.D_ID, D.D_NAME
FROM EMPLOYEE AS E LEFT JOIN DEPARTMENT AS D
ON E.D_ID = D.D_ID
UNION
SELECT E.E_ID, E.SALARY,E.D_ID, D.D_ID, D.D_NAME
FROM EMPLOYEE AS E RIGHT JOIN DEPARTMENT AS D
ON E.D_ID = D.D_ID;

-- CROSS JOIN
CREATE TABLE NAME1(S_NAME VARCHAR(10));
INSERT INTO NAME1 VALUES("JOHN"),("SARA"),("KRISH"),("BOB");

CREATE TABLE DEPT(DEPARTMENT VARCHAR(15));
INSERT INTO DEPT VALUES("IT"),("HR"),("SALES");

SELECT * FROM NAME1 CROSS JOIN DEPT;

-- SELF JOIN
SELECT A.D_ID AS D_ID1, A.D_NAME AS D_NAME1,B.D_ID AS D_ID2,B.D_NAME AS D_NAME2
FROM DEPARTMENT AS A
JOIN DEPARTMENT AS B 
ON A.D_NAME = B.D_NAME AND A.D_ID = B.D_ID;